apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rollcall-go.fullname" . }}-secret
  labels:
    {{- include "rollcall-go.labels" . | nindent 4 }}
type: Opaque
stringData:
  EDGE_USERNAME: {{ .Values.config.edgeUsername | quote }}
  EDGE_PASSWORD: {{ .Values.config.edgePassword | quote }}
  EDGE_CENTER_SERVER_SECRET: {{ .Values.config.centerServerSecret | default "" | quote }}
  TG_BOT_TOKEN: {{ .Values.config.tgBotToken | default "" | quote }}
  TG_CHAT_ID: {{ .Values.config.tgChatId | default "" | quote }}
