apiVersion: v1
kind: Service
metadata:
  name: {{ include "rollcall-go.fullname" . }}
  labels:
    {{- include "rollcall-go.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.edge.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "rollcall-go.selectorLabels" . | nindent 4 }}
